#!/usr/bin/env node
/**
 * Apply brand.json across the kit.
 *
 * Agents: edit ../brand.json, then run `npm run customize` from the repo root
 * (or `node scripts/apply-brand.mjs`). This is the only mechanical sync step.
 *
 * Writes:
 *   - css/tokens.css   (region between @@brand markers)
 *   - css/fonts.css    (@import URL)
 *   - DESIGN.md        (front-matter name, description, colors, type stacks, radii)
 *   - *.html           ([data-brand] stamps + <title data-brand-title>)
 *   - design-md.html   (via sync-design-md-embed.mjs)
 *
 * Does NOT rewrite DESIGN.md prose below the front matter (except the three
 * typography family names in backticks). Agents must still describe the brand.
 *
 * Viewing the reference site never requires this script.
 */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

function read(rel) {
  return readFileSync(join(root, rel), "utf8");
}

function write(rel, text) {
  writeFileSync(join(root, rel), text, "utf8");
  console.log(`  wrote ${rel}`);
}

function loadBrand() {
  const brand = JSON.parse(read("brand.json"));
  const required = ["name", "tagline", "description", "colors", "fonts", "rounded"];
  for (const key of required) {
    if (brand[key] == null) throw new Error(`brand.json missing "${key}"`);
  }
  for (const key of [
    "primary",
    "accent",
    "paper",
    "ink",
    "ink-deep",
    "surface",
    "on-primary",
    "on-accent",
  ]) {
    if (!brand.colors[key]) throw new Error(`brand.json colors missing "${key}"`);
  }
  return brand;
}

function applyTokens(brand) {
  const c = brand.colors;
  const f = brand.fonts;
  const r = brand.rounded;
  const k = brand.knobs || {};
  const block = `  /* @@brand:start — generated by scripts/apply-brand.mjs from brand.json. Do not edit by hand. */
  --cds-paper: ${c.paper};
  --cds-paper-deep: ${c["paper-deep"]};
  --cds-surface: ${c.surface};
  --cds-panel: ${c.panel};
  --cds-panel-deep: ${c["panel-deep"]};
  --cds-panel-soft: ${c["panel-soft"]};

  --cds-ink: ${c.ink};
  --cds-ink-deep: ${c["ink-deep"]};
  --cds-ink-muted: ${c["ink-muted"]};
  --cds-ink-soft: ${c["ink-soft"]};
  --cds-rule: ${c.rule};

  --cds-primary: ${c.primary};
  --cds-primary-deep: ${c["primary-deep"]};
  --cds-primary-soft: ${c["primary-soft"]};
  --cds-on-primary: ${c["on-primary"]};

  --cds-accent: ${c.accent};
  --cds-accent-soft: ${c["accent-soft"]};
  --cds-on-accent: ${c["on-accent"]};

  --cds-primary-1: ${c["primary-1"]};
  --cds-primary-2: ${c["primary-2"]};
  --cds-primary-3: ${c["primary-3"]};
  --cds-primary-4: var(--cds-primary);
  --cds-primary-5: ${c["primary-5"]};

  --cds-success: ${c.success};
  --cds-success-bg: ${c["success-soft"]};
  --cds-warning: ${c.warning};
  --cds-warning-bg: ${c["warning-soft"]};
  --cds-danger: ${c.danger};
  --cds-danger-bg: ${c["danger-soft"]};
  --cds-info: var(--cds-primary);
  --cds-info-bg: var(--cds-primary-soft);

  --cds-chart-1: var(--cds-primary);
  --cds-chart-2: var(--cds-accent);
  --cds-chart-3: var(--cds-success);
  --cds-chart-4: var(--cds-ink-muted);

  --cds-surface-dark: ${c["surface-dark"]};
  --cds-on-dark: ${c["on-dark"]};
  --cds-on-dark-muted: ${c["on-dark-muted"]};

  --cds-font-display: ${f.displayStack};
  --cds-font-body: ${f.bodyStack};
  --cds-font-mono: ${f.monoStack};

  --cds-weight-regular: ${f.weightRegular};
  --cds-weight-semibold: ${f.weightSemibold};
  --cds-weight-bold: ${f.weightBold};

  --cds-radius-sm: ${r.sm};
  --cds-radius: ${r.md};
  --cds-radius-lg: ${r.lg};
  --cds-radius-pill: ${r.pill};

  --cds-button-radius: ${k.buttonRadius || "var(--cds-radius-pill)"};
  --cds-heading-font: ${k.headingFont || "var(--cds-font-display)"};
  /* @@brand:end */`;

  const css = read("css/tokens.css");
  const next = css.replace(
    /\/\* @@brand:start[\s\S]*?\/\* @@brand:end \*\//,
    block,
  );
  if (next === css) {
    throw new Error(
      "css/tokens.css is missing @@brand:start / @@brand:end markers.",
    );
  }
  write("css/tokens.css", next);
}

function applyFonts(brand) {
  const css = read("css/fonts.css");
  const url = brand.fonts.googleImport;
  const next = css.replace(
    /@import url\("[^"]+"\);/,
    `@import url("${url}");`,
  );
  if (next === css && !css.includes(url)) {
    throw new Error("css/fonts.css: could not find @import url(...) to replace");
  }
  write("css/fonts.css", next);
}

function yamlQuote(value) {
  const s = String(value);
  if (/^[A-Za-z0-9_./+-]+$/.test(s) && !s.includes(" ")) return s;
  return JSON.stringify(s);
}

function applyDesignMd(brand) {
  const c = brand.colors;
  const f = brand.fonts;
  const r = brand.rounded;
  const displayStack = `${f.displayName}, Georgia, Times New Roman, serif`;
  const bodyStack = `${f.bodyName}, system-ui, sans-serif`;
  const monoStack = `${f.monoName}, ui-monospace, Consolas, monospace`;

  const head = `version: 1.0.0
name: ${brand.name}
description: >-
  ${brand.description.replace(/\n+/g, " ").trim()}
colors:
  primary: ${yamlQuote(c.primary)}
  primary-deep: ${yamlQuote(c["primary-deep"])}
  primary-soft: ${yamlQuote(c["primary-soft"])}
  accent: ${yamlQuote(c.accent)}
  accent-soft: ${yamlQuote(c["accent-soft"])}
  paper: ${yamlQuote(c.paper)}
  paper-deep: ${yamlQuote(c["paper-deep"])}
  surface: ${yamlQuote(c.surface)}
  panel: ${yamlQuote(c.panel)}
  panel-deep: ${yamlQuote(c["panel-deep"])}
  panel-soft: ${yamlQuote(c["panel-soft"])}
  ink: ${yamlQuote(c.ink)}
  ink-deep: ${yamlQuote(c["ink-deep"])}
  ink-muted: ${yamlQuote(c["ink-muted"])}
  ink-soft: ${yamlQuote(c["ink-soft"])}
  rule: ${yamlQuote(c.rule)}
  success: ${yamlQuote(c.success)}
  success-soft: ${yamlQuote(c["success-soft"])}
  warning: ${yamlQuote(c.warning)}
  warning-soft: ${yamlQuote(c["warning-soft"])}
  danger: ${yamlQuote(c.danger)}
  danger-soft: ${yamlQuote(c["danger-soft"])}
  info: ${yamlQuote(c.primary)}
  info-soft: ${yamlQuote(c["primary-soft"])}
  surface-dark: ${yamlQuote(c["surface-dark"])}
  on-primary: ${yamlQuote(c["on-primary"])}
  on-accent: ${yamlQuote(c["on-accent"])}
  on-dark: ${yamlQuote(c["on-dark"])}
  on-dark-muted: ${yamlQuote(c["on-dark-muted"])}
typography:
  display-xl:
    fontFamily: ${displayStack}
    fontSize: 3.5rem
    fontWeight: ${f.weightBold}
    lineHeight: 1.1
    letterSpacing: -0.015em
  display-lg:
    fontFamily: ${displayStack}
    fontSize: 3rem
    fontWeight: ${f.weightBold}
    lineHeight: 1.1
    letterSpacing: -0.015em
  display-md:
    fontFamily: ${displayStack}
    fontSize: 2.25rem
    fontWeight: ${f.weightBold}
    lineHeight: 1.1
    letterSpacing: -0.015em
  display-sm:
    fontFamily: ${displayStack}
    fontSize: 1.75rem
    fontWeight: ${f.weightSemibold}
    lineHeight: 1.15
    letterSpacing: -0.015em
  body-lg:
    fontFamily: ${bodyStack}
    fontSize: 1.375rem
    fontWeight: ${f.weightRegular}
    lineHeight: 1.5
  body-md:
    fontFamily: ${bodyStack}
    fontSize: 1.125rem
    fontWeight: ${f.weightRegular}
    lineHeight: 1.6
  body-sm:
    fontFamily: ${bodyStack}
    fontSize: 1rem
    fontWeight: ${f.weightRegular}
    lineHeight: 1.35
  label:
    fontFamily: ${bodyStack}
    fontSize: 1rem
    fontWeight: ${f.weightSemibold}
    lineHeight: 1.35
  meta:
    fontFamily: ${bodyStack}
    fontSize: 1rem
    fontWeight: ${f.weightBold}
    lineHeight: 1.35
    letterSpacing: 0.06em
  code:
    fontFamily: ${monoStack}
    fontSize: 1rem
    fontWeight: ${f.weightRegular}
    lineHeight: 1.55
rounded:
  sm: ${r.sm}
  md: ${r.md}
  lg: ${r.lg}
  pill: ${r.pill}`;

  const md = read("DESIGN.md");
  const match = md.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n/);
  if (!match) throw new Error("DESIGN.md missing YAML front matter");

  const oldBody = match[1];
  const prose = md.slice(match[0].length);
  const keep = oldBody.match(/\n(spacing:\n[\s\S]*)$/);
  if (!keep) throw new Error("DESIGN.md front matter missing spacing: block");

  let next = `---\n${head}\n${keep[1]}\n---\n${prose}`;
  next = next.replace(
    /\*\*Display serif\*\* \(`[^`]+`\)/,
    `**Display serif** (\`${f.displayName}\`)`,
  );
  next = next.replace(
    /\*\*Body sans\*\* \(`[^`]+`\)/,
    `**Body sans** (\`${f.bodyName}\`)`,
  );
  next = next.replace(
    /\*\*Mono\*\* \(`[^`]+`\)/,
    `**Mono** (\`${f.monoName}\`)`,
  );
  write("DESIGN.md", next);
}

function stampHtml(brand) {
  const pages = readdirSync(root).filter((f) => f.endsWith(".html"));
  for (const file of pages) {
    let html = read(file);
    let changed = false;

    const stamp = (attr, value) => {
      const re = new RegExp(
        `(<[^>]*\\bdata-brand="${attr}"[^>]*>)([\\s\\S]*?)(<\\/[^>]+>)`,
        "g",
      );
      const out = html.replace(re, (_, open, _inner, close) => {
        changed = true;
        return `${open}${escapeHtml(value)}${close}`;
      });
      html = out;
    };

    stamp("name", brand.name);
    stamp("tagline", brand.tagline);
    stamp("font-display", brand.fonts.displayName);
    stamp("font-body", brand.fonts.bodyName);
    stamp("font-mono", brand.fonts.monoName);

    const mk = brand.mediaKit || {};
    if (mk.shortName) stamp("shortName", mk.shortName);
    if (mk.boilerplate) stamp("boilerplate", mk.boilerplate);
    if (mk.oneLiner) stamp("oneLiner", mk.oneLiner);
    if (mk.website) {
      stamp("website", mk.website);
      const webHref = html.replace(
        /(<[^>]*\bdata-brand="website"[^>]*\bhref=")[^"]*(")/g,
        (_, a, b) => {
          changed = true;
          return `${a}${mk.website}${b}`;
        },
      );
      html = webHref;
    }
    if (mk.contactEmail) {
      stamp("contactEmail", mk.contactEmail);
      const mailHref = html.replace(
        /(<[^>]*\bdata-brand="contactEmail"[^>]*\bhref=")[^"]*(")/g,
        (_, a, b) => {
          changed = true;
          return `${a}mailto:${mk.contactEmail}${b}`;
        },
      );
      html = mailHref;
    }

    html = html.replace(
      /<title([^>]*)\bdata-brand-title="([^"]+)"([^>]*)>[\s\S]*?<\/title>/g,
      (_, a, page, b) => {
        changed = true;
        return `<title${a}data-brand-title="${page}"${b}>${escapeHtml(page)} — ${escapeHtml(brand.name)} Design System</title>`;
      },
    );

    if (changed) write(file, html);
  }
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function syncEmbed() {
  const result = spawnSync(process.execPath, [join(root, "sync-design-md-embed.mjs")], {
    cwd: root,
    encoding: "utf8",
  });
  if (result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);
  if (result.status !== 0) {
    throw new Error("sync-design-md-embed.mjs failed");
  }
}

function reportLeftovers(brand) {
  if (brand.name === "Example Brand") {
    console.log('\nPlaceholder check: brand.json still has name "Example Brand".');
    console.log("Set placeholder:false and rename when the fork is real.\n");
    return;
  }
  const scanFiles = [
    "DESIGN.md",
    "README.md",
    "AGENTS.md",
    ...readdirSync(root).filter((f) => f.endsWith(".html")),
  ];
  const hits = [];
  for (const file of scanFiles) {
    if (read(file).includes("Example Brand")) hits.push(file);
  }
  if (hits.length) {
    console.log('\nLeftover "Example Brand" still in:');
    for (const h of hits) console.log(`  - ${h}`);
    console.log("Rewrite DESIGN.md prose where needed.\n");
  } else {
    console.log('\nNo leftover "Example Brand" strings in scanned files.\n');
  }
  if (brand.placeholder) {
    console.log('brand.json still has "placeholder": true — set to false when customised.\n');
  }
}

const brand = loadBrand();
console.log(`Applying brand: ${brand.name}`);
applyTokens(brand);
applyFonts(brand);
applyDesignMd(brand);
stampHtml(brand);
syncEmbed();
reportLeftovers(brand);
console.log("Done. Open customize.html for the remaining checklist (prose, assets).");
